kind: pipeline
type: docker
name: Push Image

trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request
      - promote

steps:
  - name: Build and Push Image
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      username:
          from_secret: docker-user
      password:
          from_secret: docker-key
      repo: randomman552/rclone-scheduler
      tags:
          - latest
